esphome:
  name: sunton-43-test
  friendly_name: Sunton 4.3" Test

substitutions:
  home_page: lighting_1

packages:
  common: !include common.yaml
  device: github://RalphSmeets/esphome-configurations/devices/ESP32-8048S043.yaml
  layout: github://RalphSmeets/esphome-configurations/ayouts/800x480.yaml
